import pandas as pd
from notebook.descripcion_recomendaciones import describir_datos_recomendaciones
from notebook.limpieza_recomendaciones import limpiar_recomendaciones
from utils.Simulacion_Recomendaciones import simulacion_recomendaciones
from utils.simulacion_usuarios import simular_usuarios
from notebook.limpieza_usuarios import limpiar_usuarios
from utils.simulacion_sesiones import simular_sesiones
from notebook.limpieza_sesiones import limpiar_sesiones
from notebook.descripcion_sesiones import describir_datos_sesiones
from notebook.descripcion_usuarios import describir_datos_usuarios

simulaciones_usuarios = simular_usuarios(100)
simulaciones_ordenadas_usuarios = pd.DataFrame(simulaciones_usuarios)
simulaciones_limpias_usuarios = limpiar_usuarios(simulaciones_ordenadas_usuarios)
print(simulaciones_limpias_usuarios)

simulaciones_sesiones = simular_sesiones(50)
simulacion_ordenada_sesiones = pd.DataFrame(simulaciones_sesiones)
simulaciones_limpias_sesiones = limpiar_sesiones(simulacion_ordenada_sesiones)
print(simulaciones_limpias_sesiones)

describir_datos_sesiones(simulaciones_limpias_sesiones)
describir_datos_usuarios(simulaciones_limpias_usuarios)

simulacion_recomendaciones = simulacion_recomendaciones(50)
simulaciones_ordenadas_recomendaciones = pd.DataFrame(simulacion_recomendaciones)
simulaciones_limpias_recomendaciones = limpiar_recomendaciones(simulaciones_ordenadas_recomendaciones)
describir_datos_recomendaciones(simulaciones_limpias_recomendaciones)