import pandas as pd
from utils.simulacion_usuarios import simular_usuarios
from notebook.limpieza_usuarios import limpiar_usuarios
from utils.simulacion_sesiones import simular_sesiones
from notebook.limpieza_sesiones import limpiar_sesiones
from notebook.descripcion_sesiones import describir_datos
from notebook.descripcion_usuarios import describir_datos_usuarios

simulaciones_usuarios = simular_usuarios(1)
simulaciones_ordenadas_usuarios = pd.DataFrame(simulaciones_usuarios)
simulaciones_limpias_usuarios = limpiar_usuarios(simulaciones_ordenadas_usuarios)
print(simulaciones_limpias_usuarios)

simulaciones_sesiones = simular_sesiones(20)
simulacion_ordenada_sesiones = pd.DataFrame(simulaciones_sesiones)
simulaciones_limpias_sesiones = limpiar_sesiones(simulacion_ordenada_sesiones)
print(simulaciones_limpias_sesiones)

describir_datos(simulaciones_limpias_sesiones)
describir_datos_usuarios(simulaciones_limpias_usuarios)
